load data
infile 'E:\inbound\ven.csv'
insert into table ap_suppliers_int
fields terminated by ','
(VENDOR_INTERFACE_ID,
VENDOR_NAME
,SUMMARY_FLAG
,ENABLED_FLAG
,VENDOR_TYPE_LOOKUP_CODE
,ONE_TIME_FLAG
,SHIP_TO_LOCATION_ID
,BILL_TO_LOCATION_ID
,FREIGHT_TERMS_LOOKUP_CODE
,FOB_LOOKUP_CODE
,TERMS_ID
,SET_OF_BOOKS_ID
,ALWAYS_TAKE_DISC_FLAG
,PAY_DATE_BASIS_LOOKUP_CODE
,PAY_GROUP_LOOKUP_CODE
,PAYMENT_PRIORITY
,INVOICE_CURRENCY_CODE
,PAYMENT_CURRENCY_CODE)

